apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-fv6r
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0042-tenant/tkrw-pr712-0075-0042-app/devfile-sample-fv6r@sha256:94e216bee4344bff80893c7a5a312b8149d56a2e04b44463ac660dec1736dc97
        name: my-nodejs
        resources: {}
status: {}
